### ISSUE TITLE
Fix folder structure

### ISSUE THREAD

**Issue by deimos790** [deimos790/BoxSat_Continued#3]

**Comment by Kerbas-ad-astra** [comment]
I usually structure my repositories like so:

```
GameData/[folder]/patches_and_parts_and_such.cfg
Source/source_code_if_applicable.cs
readme.md (and other "administrative" files, images and such)
```

Then I can just zip up the GameData folder and use it for releases.

**Comment by deimos790** [comment]
yeah, that's what I was thinking (add the game data). I've never downloaded from my repo till today - I just assumed it came out like it went it, so to speak, but it seems to have lost a layer.
People seem to get confused if they don't see a GameData anyway (even me).
